spring.database.driver_class=org.postgresql.Driver
spring.database.url=jdbc:postgresql://localhost:5432/my_ticket_service_db
spring.database.username=postgres
spring.database.password=postgres

application.update.user=false